export const ALL_PRODUCT_REQUEST ="ALL PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS ="ALL PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL ="ALL PRODUCT_FAIL"

export const PRODUCT_DETAILS_REQUEST ="PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS ="PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL ="PRODUCT_DETAILS_FAIL"

export const CLEAR_ERRORS ="CLEAR_ERRORS"